# It's pretty safe to change these variables

## friendly project name
project_name: "gcp-vpn"

## Always Free compatable regions (2021-08-08):
# Region                     Zones         Location
# us-central1                a, b, c, f    Council Bluffs, Iowa, USA
# us-east1                   b, c, d       Moncks Corner, South Carolina, USA
# us-west1                   a, b, c       The Dalles, Oregon, USA
## Regions  that will immediately cost you money
# Region                     Zones         Location
# asia-east1                 a, b, c       Changhua County, Taiwan
# asia-east2                 a, b, c       Hong Kong
# asia-northeast1            a, b, c       Tokyo, Japan
# asia-northeast2            a, b, c       Osaka, Japan
# asia-northeast3            a, b, c       Seoul, South Korea
# asia-south1                a, b, c       Mumbai, India
# asia-southeast1            a, b, c       Jurong West, Singapore
# australia-southeast1       a, b, c       Sydney, Australia
# europe-north1              a, b, c       Hamina, Finland
# europe-west1               b, c, d       St. Ghislain, Belgium
# europe-west2               a, b, c       London, England, UK
# europe-west3               a, b, c       Frankfurt, Germany
# europe-west4               a, b, c       Eemshaven, Netherlands
# europe-west6               a, b, c       Zürich, Switzerland
# northamerica-northeast1    a, b, c       Montréal, Québec, Canada
# southamerica-east1         a, b, c       Osasco (São Paulo), Brazil
# us-east4                   a, b, c       Ashburn, Northern Virginia, USA
# us-west2                   a, b, c       Los Angeles, California, USA
# us-west3                   a, b, c       Salt Lake City, Utah, USA
zone: "us-central1-a"

## high-numbered port derived from project_id
vpn_port: "{{ 65535 | random(start=32767,seed=project_id) }}"

## A separate .ovpn file will be generated for each client
client_friendly_names:
  - "alice"
  - "bob"

## change this to get a different project ID suffix
project_id_seed: ""



# Don't change these variables unless you know what you're doing

## ensures our Project ID is unique across all of GCP
project_id_long: >-
  {{ project_name
     + '-' 
     + (
         hostvars["localhost"].active_account
         + project_id_seed
       ) | hash('sha512')
  }}
project_id: "{{ project_id_long[:30] }}"

service_account_file: "{{ playbook_dir }}/temporary_keys.json"
auth_kind: serviceaccount
env:
  CLOUDSDK_CORE_PROJECT: "{{ project_id }}"
destroy: "{{ cli_destroy | default(false) }}"
state: >-
  {{ "absent" if destroy == "true" else "present" }}
instance_public_ip: >-
  {{ hostvars.localhost.instance.networkInterfaces[0].accessConfigs[0].natIP }}

